Yelp/nerve-tools

- dockerfiles/itest/itest/Dockerfile.lucid
- dockerfiles/itest/itest/Dockerfile.trusty
- dockerfiles/itest/itest/run_itest.sh
- src/debian/changelog
- src/debian/control
- src/nerve_tools/clean_nerve.py
- src/nerve_tools/configure_nerve.py
- src/setup.py
This forces nerve-tools to install libyaml via shlibs. Also let's use CLoader for the zookeeper topo files as well (instead of just for service_configuration_lib)
> Use shlib deps

- src/debian/changelog
- src/nerve_tools/configure_nerve.py
- src/setup.py
- src/tests/configure_nerve_test.py
Currently configure_nerve uses the mode parameter for both the service mode and the healthcheck mode. This means that TCP services cannot have HTTP checks, because the hacheck uri will always be '/tcp/...'.
This change introduces a new configuration parameter called healthcheck_mode that specifies the mode of the check. If not specified, it defaults to the service mode, so it is fully backward compatible.
> Add healthcheck_mode parameter, bump version to 0.10.0

- src/debian/changelog
- src/requirements.txt
- src/setup.py
paasta-tools includes a change that nerve-tools needs in order to make the healthcheck_mode work.
> Upgrade paasta-tools, bump version to 0.10.1

- src/debian/changelog
- src/setup.py
The paasta-tools version in setup.py doesn't correspond with the one in requirements.txt.
> Fix setup version typo

- .gitignore
- .travis.yml
- Makefile
- bintray.json.in
This branch builds itest_trusty with travis, and for tagged versions, pushes the built .deb to [Bintray](https://bintray.com/yelp/paasta/nerve-tools/view).
Similar to Yelp/paasta#337
Fixes #6
> Public package build

- src/nerve_tools/configure_nerve.py
- src/tests/configure_nerve_test.py
- src/tox.ini
This removes all the hard-coded values in configure_nerve and makes them command line options, with defaults that are the same as they were previously hard-coded to.
This means it should be a drop-in replacement if you don't pass any options, but would allow for environments where hacheck doesn't run on 6666, ZK discovery files are in a different directory, or ZK clusters live at a different location type than 'superregion'.
> Less hard-coding, more options.

- src/debian/changelog
- src/nerve_tools/configure_nerve.py
- src/setup.py
@jnb This fixes the bug I saw yesterday in staging where the backup process just ran forever and ever.
> When reloading with sighups, always try to stop the nerve-backup process

- dockerfiles/itest/itest/itest.py
- src/debian/changelog
- src/nerve_tools/configure_nerve.py
- src/setup.py
- src/tests/configure_nerve_test.py
So... copying files is not atomic, which means we can kill nerve by
telling it to read a file which won't exist or will partially exist.
Let's stop doing that.
> Move nerve config rather than copy

- dockerfiles/itest/itest/itest.py
- src/nerve_tools/configure_nerve.py
- src/tests/configure_nerve_test.py
This will write nodes annotated with labels into `/nerve/all` in addition to the current locations. This will enable us to create smartstack backends using filters from the nodes in `/nerve/all`
@jolynch @jnb @solarkennedy
> write to /nerve/all for all advertise regions

- dockerfiles/itest/itest/itest.py
- src/nerve_tools/configure_nerve.py
- src/tests/configure_nerve_test.py
@jolynch @solarkennedy In order to fix the problems in https://github.com/Yelp/synapse-tools/pull/11 without using huge number of labels, we're putting the burden on nerve to add metadata for `extra_advertise` nodes.
> duplicate and annotate extra_advertise nodes with metadata

- src/nerve_tools/updown_service.py
- src/requirements.txt
- src/setup.py
- src/tests/updown_service_test.py
This makes it so that developers can do:
```bash
updown_service apollo.main:12345 down
```
And it'll do the right thing. This will help prevent the proliferation of hadown/haup in runbooks that will be hard to change if we decide to go with something other than hacheck.
> Modernize updown_service for paasta services

- dockerfiles/trusty/Dockerfile
- dockerfiles/xenial/Dockerfile
- src/debian/rules
- src/nerve_tools/updown_service.py
- src/setup.py
- src/tests/updown_service_test.py
- src/tox.ini
It turns out that check_call assumes all arguments will be strings
Lovely. This fixes it.
> Fix command when port is supplied

- src/debian/changelog
- src/nerve_tools/configure_nerve.py
- src/setup.py
- src/tests/configure_nerve_test.py
like $SERVICENAME$SERVCEPORT*, loads them as yaml, and applies them as
labels to that service on that port.
> Configure smartstack provides custom labels for services

- src/nerve_tools/updown_service.py
- src/tests/updown_service_test.py
This was causing updown_service to fail when getting and reading the
HAProxy stats csv. Unfortunately this is a pain to itest because we
don't have haproxy in the itest setup. I have confirmend the fix by
testing against a local haproxy.
> Fix bytes vs str in DictReader

- dockerfiles/itest/itest/itest.py
- src/nerve_tools/configure_nerve.py
- src/requirements.txt
- src/setup.py
- src/tests/configure_nerve_test.py
Adds a new call to get kubernetes services from paasta_tools.
Adds two new options to the service_info dict to allow us to override
the host IP and the check IP. For kubernetes we initially want the pod
IP for both and may later want a system level hacheck again.
NB: I haven't published the paasta_tools branch with `get_kubernetes_services_running_here_for_nerve` yet. So I will have to merge that first and update the paasta_tools version here before the tests pass.
> Add support for registering k8s services

- src/nerve_tools/configure_nerve.py
- src/requirements.txt
- src/tests/configure_nerve_test.py
This is part 2 of CORESERV-7915 (internal ticket). The code here requires the [changes I made in PaaSTA](https://github.com/Yelp/paasta/pull/2258) to work, that I released yesterday, before bumping the requirements to `paasta-tools==0.84.19`.
Again, added some optional data to be passed along with service registrations. If the data isn't there, it simply won't be written. Added extra fields to the testing logic and that's pretty much it.
> Write the deploy_group and paasta_instance to nerve config

- src/requirements.txt
Bump `pyyaml` to 4.2b1 and `requests` to 2.20.0 because of the security
alert.
> Bump pyyaml and requests versions because of the security alert

- src/mypy.ini
- src/nerve_tools/clean_nerve.py
- src/nerve_tools/configure_nerve.py
- src/tests/configure_nerve_test.py
- src/tox.ini
If ingress listeners for locally running paasta services are set up in Envoy, configure_nerve will read the listeners info from Envoy admin's /listener endpoint and output nerve configs for the Envoy ingress endpoints.
The nerve configs for the Envoy listener endpoints should be the same as the .v2 configs except for
* different port numbers
* different zookeeper path (/envoy/global/{service name})
> Read envoy listeners from /listeners and healthcheck paasta services through envoy

- .travis.yml
Same issue as https://github.com/Yelp/synapse-tools/pull/68
Master branch travisCI build is failing for the mypy target:
```
mypy run-test: commands[0] | mypy nerve_tools
___________________________________ summary ____________________________________
mypy: commands succeeded
congratulations :)
The command "make "$MAKE_TARGET"" exited with 0.
dpl_0
1.66s$ rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl
Fetching dpl-1.10.11.gem
Successfully installed dpl-1.10.11
Parsing documentation for dpl-1.10.11
Installing ri documentation for dpl-1.10.11
Done installing documentation for dpl after 0 seconds
1 gem installed
dpl.1
Installing deploy dependencies
Fetching dpl-bintray-1.10.11.gem
Successfully installed dpl-bintray-1.10.11
Parsing documentation for dpl-bintray-1.10.11 …
```
> Ignore mypy when deploying

- src/nerve_tools/configure_nerve.py
- src/tests/configure_nerve_test.py
Uses HTTPS to healthcheck HTTP services which are proxied via envoy. The testing refactor of meshd is still in progress which is making testing this change difficult. Shipping this PR since unhackathon is over and it might be some time before I am able to complete the testing refactor.
> Use HTTPs (when applicable) for ingress envoy healthchecks

- src/nerve_tools/configure_nerve.py
- src/tests/configure_nerve_test.py
Just check that an Envoy ingress port is set up for a local service's actual port when determining whether we should output Envoy nerve configs for a service. This ensures that services with multiple registrations will have all the registrations healthchecked.
Previously, a mapping of "{service_name}.{service_instance}.{local_host_port}" -> "Envoy ingress port" was used, but this would cause services with multiple registrations (like "service.main" and "service.alt_name") to only have one Envoy nerve config outputted. This is because Envoy's `/listeners` admin endpoint only outputs listener information under the listener name, and only one listener is set up for each service, even if it has multiple registrations.
By only checking the local host port, we lose some guarantees that the …
> Fix multiple smartstack registrations

- src/nerve_tools/configure_nerve.py
- src/tests/configure_nerve_test.py
This fixes a bug where the Envoy registrations are not getting locality labels
> fix locality labels for envoy registration

- src/requirements.txt
We've changed some kubernetes labels and need nerve to stop reading old ones.
> Bump paasta to 0.90.4

- .gitignore
- src/Makefile
- src/nerve_tools/config.py
- src/nerve_tools/configure_nerve.py
- src/nerve_tools/envoy.py
- src/nerve_tools/util.py
- src/requirements-dev.txt
- src/tests/configure_nerve_test.py
- src/tests/envoy_test.py
- src/tox.ini
Main features:
- Supports envoy ingress listeners for kubernetes backed services and adds them to nerve.conf.json accordingly.
Fixed while I was in there:
- broke out envoy stuff into envoy.py
- broke out config data classes into config.py
- replaced ip_address with host_ip or service_ip to disambiguate what the ip addr actually represents (only in new/updated code)
Testing:
- added test coverage with fails under 75%
- verified test coverage execution for newly added code
> Add envoy ingress listeners to nerve.conf.json for kubernetes services

- dockerfiles/bionic/Dockerfile
- dockerfiles/trusty/Dockerfile
- dockerfiles/xenial/Dockerfile
- src/debian/rules
- src/nerve_tools/configure_nerve.py
- src/nerve_tools/envoy.py
- src/requirements-bootstrap.txt
- src/tests/configure_nerve_test.py
- src/tests/envoy_test.py
This nerve-toosl PR is meant to be shipped with the internal CR for meshd under CORESERV-9319.  
Both meshd and nerve-tools were tested on stagef to verify ingress traffic to multiple pods for the same service on a single host works without a hitch: https://fluffy.yelpcorp.com/i/94hFVtlfzjgw4GkWdC4tHGwNTqzzGKjJ.html
> Support k8s pod ip in envoy listener name

- src/requirements.txt
cookiecutter==1.7.2 requires a requests>=2.23.0. This ended up breaking `configure_nerve` when run in our itests:
pkg_resources.ContextualVersionConflict: (requests 2.20.0 (/opt/venvs/nerve-tools/lib/python3.6/site-packages), Requirement.parse('requests>=2.23.0'), {'cookiecutter'})
Updating requests to the min required version.
> Fix version conflict breaking build

- .travis.yml
- Makefile
- dockerfiles/bionic/Dockerfile
- dockerfiles/bionic/docker-compose.yml
- dockerfiles/itest/docker-compose-bionic.yml
- dockerfiles/itest/docker-compose-trusty.yml
- dockerfiles/itest/docker-compose-xenial.yml
- dockerfiles/itest/itest/Dockerfile.bionic
- dockerfiles/itest/itest/Dockerfile.trusty
- dockerfiles/itest/itest/Dockerfile.xenial
- dockerfiles/trusty/Dockerfile
- dockerfiles/trusty/docker-compose.yml
- dockerfiles/xenial/Dockerfile
- dockerfiles/xenial/docker-compose.yml
- src/debian/rules
- src/requirements.txt
- tox.ini
Mostly for security reasons we don't want to build from public pypi
internally. We do want to use it for travis of course. Had to upgrade
docker compose to make it pass a build arg. I think I caught everything
pip does, largely copying approach by vkhromov in
https://github.com/Yelp/paasta/pull/2872
> Ensure internal yelp builds use internal pypi

- dockerfiles/bionic/docker-compose.yml
- dockerfiles/trusty/docker-compose.yml
- dockerfiles/xenial/docker-compose.yml
Dockerfiles directly mounted the gitroot rw, allowing the build to clutter the gitroot with root-owned build files.
This change isolates the build to the docker container.
> itests don't clutter gitroot

- Jenkinsfile
- dockerfiles/itest/itest/Dockerfile.bionic
- jenkins.yaml
- tox.ini
We build projects using Jenkins and Jenkinsfiles. This brings this project up-to-date with our current testing workflows.
Added 2 other fixes 
* Ensure required packages are up to date
* Ensure itests don't interfere with each other when run in parallel on the same host
> Fix internal build

- .travis.yml
By default, bintray v1 cleans the working directory before deploying
packages. However, this repo creates the `bintray.json` configuration file
during its build. `skip_cleanup` disables the cleanup behaviour.
> Fix bintray error in travis build

- src/nerve_tools/configure_nerve.py
- src/nerve_tools/envoy.py
- src/tests/envoy_test.py
When `--admin-envoy-port` is not defined, skip envoy listener discovery.
> Disable envoy lookup when admin-envoy-port is not specified

- src/requirements.txt
- tox.ini
This PR pins cryptography to v3.0 since later versions do not support OpenSSL 1.0.2, which is what we run and can't update from until we're off trusty and xenial. 
`make itest_xenial` passes now
> Pin cryptography to v3.0

- src/requirements.txt
- tox.ini
We have a very small number of xenial boxes that install this package -
cryptography==3.2 doesn't like the version of OpenSSL installed on those
boxes so lets downpin until these stragglers are gone
> Downpin cryptography to 3.0

- Jenkinsfile
- jenkins.yaml
There's internal automation that will disable Jenkins jobs that don't show up in an internal repos jenkins.yaml which is leading to the pipeline for this job getting disabled.
I've already brought this config in-house, and this is just some cleanup to not confuse us in the future
> Delete Jenkins config

- src/debian/rules
- tox.ini
For some reason dh_virtualenv couldn't find bundled libcrypto. This fixes that error. hacheck is also private now so the build may still be broken? But one thing at a time...
> Fix build libcrypto errors
